#! /bin/bash

# Esse script ira montar um ambiente todo automatizado com as configurações e tecnologias personalizadas para o uso do meu dia-a-dia

FILE=jetbrains-toolbox.tar.gz
DIRECTORY=jetbrains-toolbox-1.23.11731

sudo apt update && sudo apt clean all

sudo apt install vim neofetch htop cmatrix python3-pip build-essential gcc g++ make zsh git curl vlc -y

# Install nvm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

# Download Discord app
echo "Download Discord app"
wget -O discord.deb "https://discord.com/api/download?platform=linux&format=deb"

# Download Google-Chrome browser
echo "Download Google-Chrome browser"
wget -O google-chrome.deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

# Download vscode app
echo "Download VsCode app"
wget -O code.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

# Download Insomnia app
echo "Download Insomnnia app"
wget -O insomnia.deb "https://updates.insomnia.rest/downloads/ubuntu/latest?&app=com.insomnia.app&source=website"

# Download AppImage toolbox jetbrains
echo "Download AppImage Jetbrains Toolbox"
wget -O jetbrains-toolbox.tar.gz "https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.23.11731.tar.gz"

# Download release nvim 0.8.0
echo "Download Nvim"
wget -O neovim.deb "https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb"

sudo dpkg -i discord.deb neovim.deb google-chrome.deb code.deb insomnia.deb

chsh -s /bin/zsh

# Extract and move AppImage to Documents

# Extract tar.gz

if [ -f $FILE ]; then
	echo "$FILE exist. Extract now"
	tar -xvzf $FILE
	echo "Removing resources"
	rm -rf $FILE
fi

# Move AppImage to Documents

if [ -d $DIRECTORY ]; then
	echo "$DIRECTORY exist. Move to Documents"
	mv $DIRECTORY/jetbrains-toolbox $HOME/Documents
	echo "Removing resources"
	rm -rf $DIRECTORY
fi

#TODO Create list to remove package files

# After all install, remove packages
for app in ${applist[*]}; do
	echo 'deleting' ${app}
	rm -rf $app
done

sudo apt update && sudo apt upgrade -y

#TODO Create script for docker
#TODO Add nvm config
#TODO Add flatpak config
#TODO AstroNvim
#TODO create ssh 4 fast
#TODO create git config list
#TODO create config oh my zsh
#TODO install bat

# JAVA SDKMAN
# curl -s "https://get.sdkman.io" | bash
# source $HOME/.sdkman/bin/sdkman-init.sh
# sdk install maven
# sdk install gradle
# sdk install java 11.0.17-zulu
#
# SPOTIFY, BRAVE AND TELEGRAM
# snap install spotify brave telegram-desktop //need to confirm
#
# Install rust
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh // need be the last because need interactive
