#! /bin/bash


# Esse script ira montar um ambiente todo automatizado com as configurações e tecnologias personalizadas para o uso do meu dia-a-dia

ZSHRC=resources/.zshrc
BASHRC=resources/.bashrc
FILE=jetbrains-toolbox.tar.gz
DIRECTORY=jetbrains-toolbox-1.23.11731
NOISE=./noise.tgz

install=(terminator vim neofetch htop cmatrix python3.9 python3-pip zsh build-essential libglib2.0-0 libxcb-shape0 libxcb-shm0 libxcb-xfixes0 libxcb-randr0 libxcb-image0 libfontconfig1 libegl1-mesa libgl1-mesa-glx libxi6 libsm6 libxrender1 libpulse0 libxcomposite1 libxslt1.1 libsqlite3-0 libxcb-keysyms1 libxcb-xtest0 ibus)

for i in ${install[*]}
do
	sudo apt install $i -y
done

applist=(discord.deb slack.deb google-chrome.deb code.deb zoom.deb insomnia.deb)

# Download Discord app
echo "Download Discord app"

wget -O discord.deb "https://discord.com/api/download?platform=linux&format=deb"

# Download Slack app
echo "Download Slack app"

wget -O slack.deb "https://downloads.slack-edge.com/releases/linux/4.25.0/prod/x64/slack-desktop-4.25.0-amd64.deb"

# Download Google-Chrome browser
echo "Download Google-Chrome browser"

wget -O google-chrome.deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

# Download vscode app
echo "Download VsCode app"

wget -O code.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

# Download Zoom app
echo "Download Zoom app"

wget -O zoom.deb "https://cdn.zoom.us/prod/5.10.0.2450/zoom_amd64.deb"

# Download Insomnia app
echo "Download Insomnnia app"
wget -O insomnia.deb "https://updates.insomnia.rest/downloads/ubuntu/latest?&app=com.insomnia.app&source=website"

# Download AppImage toolbox jetbrains
echo "Download AppImage Jetbrains Toolbox"

wget -O jetbrains-toolbox.tar.gz "https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.23.11731.tar.gz"

# Download release NoiseTorch
echo "Download NoiseTorch"

wget -O noise.tgz "https://github.com/lawl/NoiseTorch/releases/download/0.11.5/NoiseTorch_x64.tgz"

for app in ${applist[*]}
do
	sudo dpkg -i $app
done

# Extract and move AppImage to Documents

# Extract tar.gz

if [ -f $FILE ]; then
	echo "$FILE exist. Extract now"
	tar -xvzf $FILE
	echo "Removing resources"
	rm -rf $FILE
fi

# Move AppImage to Documents

if [ -d $DIRECTORY ]; then
	echo "$DIRECTORY exist. Move to Documents"
	mv $DIRECTORY/jetbrains-toolbox $HOME/Documents
	echo "Removing resources"
	rm -rf $DIRECTORY
fi

# Extract NoiseTorch

if [ -f $NOISE ]; then
	echo "$NOISE exist. Extract now"
	tar -C $HOME -xzf $NOISE
	# Depending on your desktop environment you may need to wait for it to rescan for applications, or tell it to do a refresh now.
	gtk-update-icon-cache
	# Give it the required permissions with setcap
	sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch
	echo "Removing resources"
	rm -rf $NOISE
fi

# Install Obsidian via flatpack

flatpak install flathub md.obsidian.Obsidian

# Install pre-commit

pip install pre-commit

# After all install, remove packages
for app in ${applist[*]}
do
	echo 'deleting' ${app}
	rm -rf $app
done

sudo apt update && sudo apt upgrade -y

# Move .bashrc and .zshrc with actual update

if [ -f $BASHRC ]; then
	echo "Copy .bashrc to home"
	cp $BASHRC $HOME/
fi

if [ -f $ZSHRC ]; then
	echo "Copy .zshrc to home"
	cp $ZSHRC $HOME/
fi
