#! /bin/bash

# Esse script ira montar um ambiente todo automatizado com as configurações e tecnologias personalizadas para o uso do meu dia-a-dia

FILE=jetbrains-toolbox.tar.gz
DIRECTORY=jetbrains-toolbox-1.23.11731

# Add repo Node 16x
echo "Add repository Node 16x"

curl -fsSL https://deb.nodesource.com/setup_16.x | sudo bash -

# Add repo Yarn package manager
echo "Add repository Yarn package manager"

curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update && sudo apt clean all

sudo apt install terminator vim neofetch htop cmatrix python3.10 python3-pip build-essential nodejs gcc g++ make yarn zsh git curl -y

# Download Discord app
echo "Download Discord app"
wget -O discord.deb "https://discord.com/api/download?platform=linux&format=deb"

# Download Google-Chrome browser
echo "Download Google-Chrome browser"
wget -O google-chrome.deb "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

# Download vscode app
echo "Download VsCode app"
wget -O code.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

# Download Insomnia app
echo "Download Insomnnia app"
wget -O insomnia.deb "https://updates.insomnia.rest/downloads/ubuntu/latest?&app=com.insomnia.app&source=website"

# Download AppImage toolbox jetbrains
echo "Download AppImage Jetbrains Toolbox"
wget -O jetbrains-toolbox.tar.gz "https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.23.11731.tar.gz"

# Download release nvim 0.8.0 
echo "Download Nvim"
wget -O neovim.deb "https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.deb"

sudo dpkg -i discord.deb neovim.deb google-chrome.deb code.deb insomnia.deb

chsh -s /bin/zsh

# Extract and move AppImage to Documents

# Extract tar.gz

if [ -f $FILE ]; then
	echo "$FILE exist. Extract now"
	tar -xvzf $FILE
	echo "Removing resources"
	rm -rf $FILE
fi

# Move AppImage to Documents

if [ -d $DIRECTORY ]; then
	echo "$DIRECTORY exist. Move to Documents"
	mv $DIRECTORY/jetbrains-toolbox $HOME/Documents
	echo "Removing resources"
	rm -rf $DIRECTORY
fi

#TODO Create list to remove package files

# After all install, remove packages
for app in ${applist[*]}
do
	echo 'deleting' ${app}
	rm -rf $app
done

sudo apt update && sudo apt upgrade -y

#TODO Create script for docker
#TODO Create script for Java
#TODO Add nvm config
#TODO Add flatpak config
#TODO snap -spotify and brave browser
#TODO VLC
#TODO Telegram-desktop snap 
#TODO Rust
#TODO AstroNvim
#TODO create ssh 4 fast
#TODO create git config list
#TODO create config oh my zsh
#TODO install bat
